- name: Just force systemd to reread configs
  ansible.builtin.systemd_service:
    daemon_reload: true
  listen: "systemctl daemon-reload"

- name: Restart ydbd-storage
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: ydbd-storage
    state: restarted
  listen: "restart ydbd"
